// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IStoreServer is an autogenerated mock type for the IStoreServer type
type IStoreServer struct {
	mock.Mock
}
