// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	types "github.com/REST-API-Test/types"
	mock "github.com/stretchr/testify/mock"
)

// IUsecase is an autogenerated mock type for the IUsecase type
type IUsecase struct {
	mock.Mock
}

// GetCustomerOrders provides a mock function with given fields: _a0
func (_m *IUsecase) GetCustomerOrders(_a0 types.CustomerOrderParams) ([]types.Order, error) {
	ret := _m.Called(_a0)

	var r0 []types.Order
	if rf, ok := ret.Get(0).(func(types.CustomerOrderParams) []types.Order); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(types.CustomerOrderParams) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderHistory provides a mock function with given fields: _a0
func (_m *IUsecase) OrderHistory(_a0 types.DateRange) ([]types.DateBucket, error) {
	ret := _m.Called(_a0)

	var r0 []types.DateBucket
	if rf, ok := ret.Get(0).(func(types.DateRange) []types.DateBucket); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.DateBucket)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(types.DateRange) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceOrder provides a mock function with given fields: _a0
func (_m *IUsecase) PlaceOrder(_a0 types.OrderRequest) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.OrderRequest) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
